### ISSUE TITLE
Scrub private repo paths 

### ISSUE THREAD

**Issue by andresoro** [AirspaceTechnologies/go-env#1]
https://github.com/AirspaceTechnologies/go-env/blob/e3a77f6a4e9474aa83725e24145c63b5703489dc/docker-compose.yml#L9

not sure how this one works
https://github.com/AirspaceTechnologies/go-env/blob/e3a77f6a4e9474aa83725e24145c63b5703489dc/.golangci.yml#L32

**Comment by jose-airspace** [comment]
The docker-compose.yml file one is ok but I removed the one from .golangci.yml
